name: Fetch random quote 

on:
  workflow_dispatch:

jobs:
  use-action:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Use My Custom Action for fetching
      uses: RndmCodeGuy20/actions-test-fb@main
